### ISSUE TITLE
Snip endpoints do not precisely follow cursor

### ISSUE THREAD

**Issue by JoelHobson** [cdrani/chorus#192]
**Describe the bug**
When I attempt to set the start and end points for a snip, the music seeks as I change the endpoints. This leads to a brief freeze in the browser that results in the endpoints jumping between positions rather than moving smoothly. I've tested this in both Firefox and Chrome.

**To Reproduce**
1. Open the Chorus menu
2. Set snip start and endpoints by clicking and dragging. Start by dragging a relatively long distance, and then progressively shorter ones.

**Expected behavior**
The start/end point smoothly follows the cursor

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Firefox
 - Version: 
   - Extension: 1.18
   - Firefox: 120.0.1
   - Chrome: 120.0.6099.63

**Additional context**
I'm using this on a Surface Pro 8 with 8GB of RAM, so it's conceivable that this is an issue with my computer's performance. I'm also using a touchpad rather than a mouse which could make precise seeking harder. 

I think there may be two possible solutions here:
1. Don't update the track's position until the user releases the mousebutton instead of doing it as the mouse moves. I'd expect this make the slider move smoothly. 
2. Allow the user to enter exact time values for the start and endpoints so that the slider is optional. I'd actually really like this in addition to 1. My use case is for learning song parts on guitar, so most of my snips are going to be around one or two seconds and change frequently. Since the bar to select the endpoints is small, it's fairly difficult to pick a segment that short. For example, on a five minute track, the start and endpoints are more or less visually overlapping for a five second snip. Since I intend to use this primarily on a laptop without a mouse attached, this would also help with the lack of accuracy from using a touchpad.

**Comment by cdrani** [comment]
I am aware of this. It's not intuitive, but once a User has focused on the thumb, they can use right and left arrows keys for more precise dragging (1 sec per arrow click). However, I can see how the issue is further compounded within the use-case of a tablet. 

In previous iterations and designs, I had inputs for start and end times for more precise settings of snips, but I removed it as I thought I would get to implementing Multi-Snips (#6) sooner, which would require a ui rework anyhow. Multi-Snips is a lower priority now, so I can get to this first.

Thanks for raising this up to signify it's importance in my priority list
