### ISSUE TITLE
Extension suddenly crashes after installation

### ISSUE THREAD

**Issue by sstephanyy** [cdrani/chorus#210]
**Describe the bug**
Sudden Disappearance of Features and Icon in Chorus Extension Post-Installation

**To Reproduce**
1. I accessed the Chrome Web Store and installed the Chorus extension.
2. I attempted to explore the extension’s features to understand how it works.
3. Before I could test it, the features and the extension’s icon disappeared from the user interface.

**Expected behavior**
The extension should work

**Screenshots**
![image](https://github.com/cdrani/chorus/assets/128330097/173eb243-6cad-413a-a73b-a47700a9fa84)

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version: 124.0.6367.202

**Comment by cdrani** [comment]
@sstephanyy: Truly sorry about this. I introduced a bug in the latest release yesterday. I have already pushed a fix way earlier today, but it's currently in review. Hopefully, it gets updated in CWS within just a few hours. 

For an immediate fix until then, we have the following options:
1. If you have FireFox, the fix is live in the [FireFox addon store](https://addons.mozilla.org/eu/firefox/addon/chorus-spotify-enhancer/)
2. You can download the latest release as a zip file and load it manually [latest chrome](https://github.com/cdrani/chorus/releases/tag/v1.22.2). 

Sorry once again. Thanks for reporting this and being patient while this is being remedied. 🙏

**Comment by sstephanyy** [comment]
@cdrani: No worries, I understand ☺️.  Bugs happen, it's just part of the gig. In the meantime, I'll explore the options provided for an immediate fix. Fingers crossed it gets through review smoothly!

I'd like to express my interest in contributing to this project. It sounds like an amazing initiative, and I'd love to be a part of it. Please let me know if there's anything specific I can assist with to help expedite the resolution process.

**Comment by cdrani** [comment]
Sure, I would welcome any contributions. 

This would be a good starting issue: #207.

**Comment by sstephanyy** [comment]
I will try to solve it. It is my first time contribuiting to an open source project 😁. But I'll do my best

**Comment by cdrani** [comment]
Awesome! I'll be glad to give a helping hand when you have questions along the way. Post any questions/comments in the issue and I'll respond there. This will also give a good chance to write up documentation on how to make contributions. Good luck!


Closing this issue now as fix is live.
